### ISSUE TITLE
v98 Install error

### ISSUE THREAD

**Issue by mhebrard** [Ensembl/ensembl-vep#617]
I encounter some issues (perl modules not found or wrong version) when installing VEP on a remote machine.

To help troubleshoot, I try to install VEP on a fresh conda envionment

###  Here my conda env
```yml
name: vep
channels:
- bioconda
- conda-forge
dependencies:
- gxx_linux-64
- libgcc
- make
- perl
- perl-archive-zip
- perl-DBI
```

### Here my commands
```sh

# Activate env
conda activate vep
# Clone VEP
git clone https://github.com/Ensembl/ensembl-vep.git
# Browse
cd ensembl-vep
# Install vep
perl INSTALL.pl
```

### Here the error
```txt

WARNING: DBD::mysql module not found. VEP can only run in offline (--offline) mode without DBD::mysql installed

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements

Hello! This installer is configured to install v98 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
ERROR: Unable to unpack file ./Bio/tmp/release-1-6-924.zip without Archive::Extract or tar/unzip/gzip
```
